### ISSUE TITLE
Does not work from ZIP download

### ISSUE THREAD

**Issue by yam655** [veltzer/openbook#104]
The make file defaults to using `git` calls _and_ `find` calls to get the filenames.

Please consider using `$(wildcard)` instead. You don't need to fork an external process. (It's a GNU extension, but you're already using `${filter}` and `${subst}`, so you're already using GNU extensions.)

Right now, you need to check for the `.git` directory before trying to run the `git ls` and `git grep` commands. Since this isn't done, it just totally breaks if you download the ZIP instead of cloning it.

**Comment by veltzer** [comment]
Will fix.

**Comment by veltzer** [comment]
Git is not longer a prereq for building.
