### ISSUE TITLE
ParamCreator import

### ISSUE THREAD

**Issue by bthcode** [veltzer/openbook#110]
Getting the following error on make:

    ImportError: cannot import name 'ParamCreator' from 'pytconf.config' 

Looks like the import in wrapper_lilypond.py should be:

    from ParamCreator.param import ParamCreator

**Comment by veltzer** [comment]
The project builds on every commit without this problem.
I suspect you have an old python module.
Please update your pytconfig:
$ pip install --upgrade pytconf
and let me know.

**Comment by bthcode** [comment]
That fixes it.  Thanks very much!

(and thanks for the cool project - i'm poking around for what it would take
to make a bass clef build)

**Comment by veltzer** [comment]
that's cool. If you find how to do it please give me pull request...:)
