### ISSUE TITLE
templar package

### ISSUE THREAD

**Issue by eudoxos** [veltzer/openbook#91]
I am unable to locate the templar package on Ubuntu; I installed templar using `pip3 install templar`, but it seems to be name-coincidence and no what is really needed --

```
Makefile:1: /usr/share/templar/make/Makefile: No such file or directory
```

I am running Ubuntu 14.10. Googling `/usr/share/templar/make/Makefile` only returns pages of this or related projects. What is happening?

**Comment by veltzer** [comment]
You can get it here:
https://launchpad.net/~mark-veltzer/+archive/ubuntu/ppa

**Comment by davehofmann** [comment]
Hi, I just tried installing `templar` on Mac OS X. Unfortunately this is not possible because your ppa can not be added:

```
sudo add-apt-repository ppa:mark-veltzer/ppa
sudo: add-apt-repository: command not found
```

I also tried to use homebrew, without success. Is there another way to build on OS X?

**Comment by veltzer** [comment]
You can download the source code and compile yourself (make, sudo make install).
I don't have Mac OS X...:(

**Comment by davehofmann** [comment]
Unfortunately I can't compile on OS X. Make outputs:
```
make: ./src/templar_cmd: Command not found
make: ./src/make_helper: Command not found
doing [all]
make: Nothing to be done for `all'.
```
When running `templar_cmd` independently, the output is:
```
-bash: ./templar_cmd: /usr/bin/python3: bad interpreter: No such file or directory
```
For security reasons, `/usr/bin` may not be modified anymore on OS X 10.11, so I can't symlink my python in there. Mine is installed in `/usr/local/bin`. Can I parameterize the command or the make script somehow?

**Comment by veltzer** [comment]
Unfortunately no. But you can change it manually.
I need to add an option to configure where your python is.

**Comment by yam655** [comment]
Instead of directly calling python3 in any particular path, you can use: `/usr/bin/env python3`

This is guaranteed to find python3 on the PATH for any POSIX system. (Including macOS.)

**Comment by veltzer** [comment]
templar has been dropped as prereq.
