### ISSUE TITLE
Make fails w/out /usr/share/templar/Makefile

### ISSUE THREAD

**Issue by shaiguitar** [veltzer/openbook#92]
As per https://github.com/veltzer/openbook/blob/master/Makefile#L1

I don't want to mindlessly submit a PR if it's necessary for you, but at least as an FYI it does block using `make` out of the box. I can remove the line myself and then `make debug_me` does show the env, or so it seems. But in any case it's more of an FYI than anything too substantiative. 

Feel free to close this.

This repo is nice. Great work, thank you!

**Comment by veltzer** [comment]
You need the templar package. For ubuntu you can get it from here:
https://launchpad.net/~mark-veltzer

**Comment by veltzer** [comment]
templar has been dropped as prereq.
