### ISSUE TITLE
Problems running make

### ISSUE THREAD

**Issue by hsitz** [veltzer/openbook#94]
Thanks for this project but I'm not sure I can get off the ground with it.  I just wanted to let you know of a few problems I ran into trying to get the build system to work, which may be representative of problems other people have.

I'm running Ubuntu 14.04 which has Python 3.4.  Maybe there's something simple I can do, but system is unfamiliar and at this point I really can't tell.  It is nice just to have the song pdf's, though, and even if I don't get things going I can find some other way to plumb the mako files for the .ly source (one reason for looking at this is to get up to speed coding jazz standards with Lilypond.
1.  The main readme says I can run ./scripts/ubuntu_install.py to install necessary packages, but I was unable to find any script with that name.
2.  I eventually discovered that I needed to install the 'templar' module, found that info here at  github in issues section but didn't notice it in the docs.
3.  After getting some errors, I manually went through install_deps.py, install2_deps.py, and install3_deps.py in templar package.  It downloaded a couple of modules.  It gave 404 errors for the sample files from the veltzer website, so I ended up commenting out those lines.
4.  When I run tdefs.py in /usr/share/templar/templardefs manually I get an empty file.  I assume this means something's not right.
## 5.  When I run 'make' examples I get error message below, and checking manually I find that the get_mod_list() function returns an empty list: 

Traceback (most recent call last):
  File "/usr/bin/templar_cmd", line 15, in <module>
    templar.cmdline.cmdline()
  File "/usr/lib/python3/dist-packages/templar/cmdline.py", line 97, in cmdline
    print(' '.join(templar.api.get_all_deps()))
  File "/usr/lib/python3/dist-packages/templar/api.py", line 67, in get_all_deps
    for m in get_mod_list():
  File "/usr/lib/python3/dist-packages/templar/api.py", line 49, in get_mod_list
    m=ml.load_module()
AttributeError: 'NoneType' object has no attribute 'load_module'
doing [out/tools.stamp]
Traceback (most recent call last):
  File "/usr/bin/templar_cmd", line 15, in <module>
    templar.cmdline.cmdline()
  File "/usr/lib/python3/dist-packages/templar/cmdline.py", line 89, in cmdline
    d=templar.api.load_and_populate()
  File "/usr/lib/python3/dist-packages/templar/api.py", line 54, in load_and_populate
    for m in get_mod_list():
  File "/usr/lib/python3/dist-packages/templar/api.py", line 49, in get_mod_list
    m=ml.load_module()
AttributeError: 'NoneType' object has no attribute 'load_module'

**Comment by veltzer** [comment]
The templar package should be installed from launchpad as a debian package. It is here:
https://launchpad.net/~mark-veltzer
Install it and then just issue "make" when you download the openbook source code.
It should built. Let me know.

The README is old. I will fix it.

**Comment by hsitz** [comment]
Thanks.  I'm not sure what 'installed from launchpad' means.  I installed the templar package using apt-get after adding your ppa repository (as described on launchpad link) and it seemed to install fine.  Is that 'installing from launchpad'?

When I run it in Idle the function:  pkgutil.iter_modules()  returns a long list that does include the templar module (but nothing at all on the templardefs path).  So not surprisingly when I run pkgutil.iter_modules(path=['templardefs']) I get an empty result.

**Comment by veltzer** [comment]
Installing from launchpad is exactly what you did.
I will check with python3.4 to see if I can recreate your problem...

**Comment by veltzer** [comment]
This issue is dead since templar is no longer a prereq. The build runs well on all ubuntus.
