### ISSUE TITLE
Please facilitate installation of templar

### ISSUE THREAD

**Issue by ghost** [veltzer/openbook#97]
Hi @veltzer 

great project, let's see if I can contribute. But before I need to `make` it.

This is for ubuntu, but I'm using debian jessie stable
https://launchpad.net/~mark-veltzer/+related-packages

I hope that with pip we facilitate the others to run `make` without problems. I don't know how to get the source to compile myself (if there are requirements), but if templar is a python thing, I propose to have it as a pip package (I never did that, but I think it is very easy) `pip3 install templar_openbook` (templar is a python package already).

Please, help, this way, we can be more people building openbook

**Comment by veltzer** [comment]
Thank you pedro. You are absolutely right that I should have the option of installing templar as a pip package and this is already on my TODO list. You are correct, what can I say?!?

Please bear with me until I get this done...

**Comment by veltzer** [comment]
Templar has been dropper as prereq.
