### ISSUE TITLE
Compiling to Bb, Eb, etc.

### ISSUE THREAD

**Issue by kach** [veltzer/openbook#99]
Would it be possible (or is it already possible) to compile copies in Bb, Eb, and bass clef? I feel Lilypond should allow this relatively easily, but I'm not familiar enough with the structure of this project to know for sure.

P.S. Thanks for an amazing resource! :-)

**Comment by veltzer** [comment]
Still not. It is on my TODO list but I haven't gotten around to it. It was one of the reasons I started this project...:)

**Comment by Hardmath123** [comment]
Ahh… well, good luck with that! I would love to see it happen. :-)

**Comment by sirsurthur** [comment]
Great project thank you.

Did you make any progress on this feature request ?

Best wishes

**Comment by veltzer** [comment]
no yet.

**Comment by brunoscherrer** [comment]
As I have done it for myself, here is a simple (probably not-so-clean) patch to compile the jazz open book in any other tonality.
Replace the file include/common.ly.mako by the one there (forked repository): https://github.com/brunoscherrer/openbook/blob/master/include/common.ly.mako
Then prior to compilation (by make), you may edit this file and replace the 'c' tonality by 'bes' (for B-flat) or 'ees' for (E-flat).
[ For some scores, there might need to further transpose by an octave to get a nice result. An octave up in B-flat can be done by writing "bes' "; an octave down in E-flat can be done by replacing 'c' by "ees, ".

**Comment by veltzer** [comment]
Thank you for this. I will check it out.

**Comment by veltzer** [comment]
Checked in your change for include/common.ly.mako.

Thanks for the code.

This is issue is now closed although I will reopen it later when I make a system to allow to configure many parameters before the build (enable/disable lyrics, enable/disable rehersal marks etc).
